hackOnlineMode = true
hackEarlySend = false
hackMessageChain = true
disconnectMessage = "This server requires you to connect through the Velocity proxy."
secret = "smp-vF7kXq2mN9pRwL4tJhBcYeAsDuZi3G8n"
