#Minecraft server properties
#Wed Apr 29 22:30:08 CEST 2026
accepts-transfers=false
allow-flight=true
broadcast-console-to-ops=false
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=peaceful
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:flat
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=S3pTaAnYBKxbJIz7MVhNbJlzqdM6VT4eRcrdSQC0
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=60
max-tick-time=60000
max-world-size=1000
motd=Lobby
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=aYG12mIV0S3KJvM7ouhYRU3tjF2BNIx
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25566
simulation-distance=12
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
